name: show-directory
on: 
  - push
  - pull_request
env:
  CI: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install

      - run: npm run lint
      - name: add make install
        run: make install
      - name: add make setup 
        run: make setup 
      - name: add make test  
        run: make test 
      - name: add make lint   
        run: make lint

      - uses: hexlet-components/hello-from-hexlet-action@release 
